apiVersion: v1
kind: Service
metadata:
  name: athlete-ai-service
spec:
  selector:
    app: athlete-ai-gke
  ports:
    - name: backend
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000